# This is a basic workflow that is manually triggered

name: Update LibreOffice

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install rsync
        run: sudo apt-get -y install rsync
      - uses: actions/checkout@v2
        with:
          path: "."
      - name: Run downloader
        run: bash <(curl -s https://raw.githubusercontent.com/alexyorke/oss_rss/master/libreoffice/downloader.sh)
      - uses: EndBug/add-and-commit@v4
        with:
          message: "Update LibreOffice"
          add: "*"
          cwd: "."
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
