# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install rsync
        run: sudo apt-get -y install rsync
    # Runs a single command using the runners shell
      - name: Run downloader
        run: bash <(curl -s https://raw.githubusercontent.com/alexyorke/oss_rss/master/libreoffice/downloader.sh)
